### ISSUE TITLE
Cover art setup

### ISSUE THREAD

**Issue by 1audio** [eisnerd/mupeace#1]
I need (and others probably as well) pretty explicit instructions for setting up to use local cover art. I followed what seems to be the instructions and it doesn't seem to find the art. I have made available on the network a directory on the player with access to the music directories. I have tried many variations but none work. 
I have tried:
ip address/Music (the accessible directory- can be reached from a browser)
/home/Music  the directory the music is in.
ip address/home/Music

Is there something I missed?

 I can get cover art with  mpod, mpad and gmpc so it should not be an issue with the host system.

**Comment by eisnerd** [comment]
[MPDroid settings](https://github.com/abarisain/dmix/wiki/Album-Art-on-your-LAN#wiki-mpdroid-settings) is fairly explicit about the settings to use, though a few extra examples wouldn't go amiss. I don't know what the equivalence between MPoD and MPDroid/Mupeace settings is.

Basically, for a track whose MPD path is `arb/bar/01 foo.flac`, MPDroid/Mupeace will try `http://[MPD server hostname]/[Path to music]/arb/bar/[Cover filename]` and then for some variations on `[Cover filename]`. For the example in the wiki,

```
/home/mafrosis/MP3/rab/boo/01 far.mp3
```

would have MPD path

```
rab/boo/01 far.mp3
```

due to the MPD server being configured with a `music_directory` of

```
/home/mafrosis/MP3/
```

The nginx config would serve

```
/home/mafrosis/MP3/rab/boo/folder.jpg
```

as

```
http://192.168.1.102/cover-art/rab/boo/folder.jpg
```

which will be found by MPDroid/Mupeace if `[MPD server hostname]` is `192.168.1.102` and `[Path to music]` is `cover-art`.

If you have the web server configured to serve the MPD music directory at `/`, like the lighttpd example on the wiki, so that the above image would be available from

```
http://192.168.1.102/rab/boo/folder.jpg
```

you would leave `[Path to music]` blank.

After a long delay, I have checked that Mupeace, for me, finds the same cover art as MPDroid. Perhaps its differences to other MPD clients that are confusing. Projects like Voyage MPD and Volumio, if successful, will make it easier for clients to work out of the box with a normal MPD setup, by providing a norm.

**Comment by dddesign** [comment]
this still quite old discussion, but I have the same problem: local coverart dont show up in mupeace. the settings should be right (dir "music/", filename "Folder.jpg") and these images are accesible by browser eg. http://192.168.1.44/music/Joy%20Denalane/Born%20and%20Raised/Folder.jpg (by the way: with Mpdroid it's working with these settings). any help or tip?

**Comment by eisnerd** [comment]
It's hard to tell from that exactly what is wrong here. It works for me with "Path to music" set to "music/" (if I configure my web server appropriately) or empty (with a slightly different web server configuration). There are a lot of variables, though, like the on-disk path to the music, mpd's `music_directory` setting, the "Path to music" setting, the default and custom art filenames, web servers case sensitivity, path encodings and probably some factors that I haven't considered.

It's so long since this code base was last reconciled with MPDroid, due to extensive refactoring in that project, that I have no idea how their cover downloads work now. Originally, Mupeace worked exactly the same as MPDroid except for a few extra filenames that Mupeace would check in addition to MPDroid's default ones and the custom one from the settings, so Mupeace would fetch art at least whenever MPDroid would be able to.

I'm happy to investigate further if you're interested in looking at it together. Are you comfortable with `adb logcat` and/or the shell? You can check what URLs Mupeace is trying with `adb` and you can see what paths mpd is giving it by running this somewhere:

```
MPD_HOST=192.168.1.44 mpc -f %file% current
```

For instance if that said
```
music/Joy Denalane/Born and Raised/3. Be Real.flac
```
instead of 
```
Joy Denalane/Born and Raised/3. Be Real.flac
```

then you would want a blank "Path to music" and either "Folder.jpg" in "Cover filename" or a case insensitive web server ("folder.jpg" is in the default list but not "Folder.jpg"). It would be better if Mupeace could fall back to using index pages to implement its own case insensitivity or wildcards, but at the moment it has to derive the exact url from its settings.

One unintended thing I have noticed is that the most or all of the art settings don't take effect until the app is restarted.
